require('config.theme')
require('config.github-copilot')
require('config.telescope')
require('config.treesitter')
require('config.sad')
require('config.autopairs')
require('config.nvim-tree')
-- require('config.bufferline')
require('config.lsp')
require('config.gitsigns')
require('config.transparent')
require('config.statusline')
require('config.marks')
require('config.indent-blankline')
require('config.pretty-fold')
require('config.alpha')
